package model.pojo;
// Generated 06-Feb-2015 15:31:02 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

    private Integer idCart;
    private User user;
    private Set cartbooks = new HashSet(0);

    public Cart() {
    }

    public Cart(User user) {
        this.user = user;
    }

    public Cart(User user, Set cartbooks) {
        this.user = user;
        this.cartbooks = cartbooks;
    }

    public Integer getIdCart() {
        return this.idCart;
    }

    public void setIdCart(Integer idCart) {
        this.idCart = idCart;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Set getCartbooks() {
        return this.cartbooks;
    }

    public void setCartbooks(Set cartbooks) {
        this.cartbooks = cartbooks;
    }

}
