package model.pojo;
// Generated 06-Feb-2015 15:31:02 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Cartbook generated by hbm2java
 */
public class Cartbook  implements java.io.Serializable {


     private Integer idCartbook;
     private Cart cart;
     private Book book;
     private int quantity;
     private Date date;
     private String status;

    public Cartbook() {
    }

    public Cartbook(Cart cart, Book book, int quantity, Date date, String status) {
       this.cart = cart;
       this.book = book;
       this.quantity = quantity;
       this.date = date;
       this.status = status;
    }
   
    public Integer getIdCartbook() {
        return this.idCartbook;
    }
    
    public void setIdCartbook(Integer idCartbook) {
        this.idCartbook = idCartbook;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


