package dto;
// Generated 06-Jan-2015 21:57:28 by Hibernate Tools 3.6.0

import java.io.Serializable;
import model.pojo.Book;
import org.springframework.web.multipart.MultipartFile;



// Generated 06-Jan-2015 21:57:28 by Hibernate Tools 3.6.0


/**
 * User generated by hbm2java
 */



public class AddBookForm implements Serializable{


     private Book book;
     private MultipartFile image;

    public AddBookForm() {
    }

    public AddBookForm(Book book, MultipartFile image) {
       this.book = book;
       this.image = image;
    }
   
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    
    public MultipartFile getImage() {
        return this.image;
    }
    
    public void setImage(MultipartFile image) {
        this.image = image;
    }


}


