package dto;
// Generated 06-Jan-2015 21:57:28 by Hibernate Tools 3.6.0

import model.pojo.User;



// Generated 06-Jan-2015 21:57:28 by Hibernate Tools 3.6.0


/**
 * User generated by hbm2java
 */



public class LoginForm {


    private String emailOrLogin;
    private String password;

    public LoginForm() {
    }
    
    public LoginForm(String email, String password) {
        this.emailOrLogin = email;
        this.password = password;
    }

    public String getEmailOrLogin() {
        return this.emailOrLogin;
    }
    
    public void setEmailOrLogin(String email) {
        this.emailOrLogin = email;
    }
    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
     
     
}


