package dto;
// Generated 06-Jan-2015 21:57:28 by Hibernate Tools 3.6.0

import model.pojo.User;



// Generated 06-Jan-2015 21:57:28 by Hibernate Tools 3.6.0


/**
 * User generated by hbm2java
 */



public class RegistrationForm {


     private User user;
     private String confirmPassword;

    public RegistrationForm() {
    }

    public RegistrationForm(User user, String confirmPassword) {
       this.user = user;
       this.confirmPassword = confirmPassword;
    }
   
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public String getConfirmPassword() {
        return this.confirmPassword;
    }
    
    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }


}


